spring:
  application:
    name: N.I.B # Nome da sua aplicação
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 251084
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect
