global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "api-challenge"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["nib:8082"]

  - job_name: "rabbitmq"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rabbitmq:15692"]
