spring:

  application:
    name: N.I.B
#  datasource:
#    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
#    username: rm552669
#    password: fiap24
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:sqlserver://sqlserver-global.database.windows.net:1433;database=NIM-2TDSPR-GlobalSolution;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: NIM
    password: devops@Fiap2tds
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      "[hibernate.generate_statistics]": false
springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8082