spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    name: N.I.B

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 251084
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        message-converter: jackson2JsonMessageConverter
      deserialization:
        trusted-packages: com.fiap.N.I.B.model


springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret-key: 890uirwjggifokrwjpgeo5yldfsopgis80f7erw8fuyw9f8ew9f7w4r67347f397tyfg347f367ferw7fr7efger77rtgw7erfw7yfeuyfwe67rfwef67w78erfwe7
