spring:
  application:
    name: N.I.B
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 240564
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

springdoc:
  api-docs:
    path: /api-docs